---
- name: Tuesday Challenge
  hosts: planetexpress
  connection: ssh
  gather_facts: yes

  tasks:
   - apt:
       name: sl
       state: present
     name: using apt to install sl
     register: result
     become: yes

   - name: print out result
     debug:
       var: result.cache_update_time

