---
- name: A simple file playbook
  hosts: planetexpress
  gather_facts: yes
  connection: ansible.builtin.ssh

  tasks:
   - name: make a directory
     ansible.builtin.file:
       path: ~/output/
       state: directory

   - name: use shell module with wildcarding
     ansible.builtin.shell: echo $HOME >> ~/output/path.txt

