---
- name: looping across a list with "loop"
  hosts: localhost
  connection: local
  gather_facts: false
       
  tasks:
   - name: "Learning about the debug module"
     ansible.builtin.debug:
       msg: "Debug module allows us to print to the screen --> {{ item }}"
     loop:
     - "1) A hyphen represents an item on a list"
     - "2) So the second item on the list is this"
     - "3) Whereas this would be the third"
     - "4) item var is always replaced by an item from the loop list"

